In [70]:
import numpy as np 
import pandas as pd 
import matplotlib.pyplot as plt 
import seaborn as sns
sns.set()

In [71]:
df=pd.read_csv("car_evaluation.csv",header=None)
df

0      1      2     3      4     5      6
0     vhigh  vhigh      2     2  small   low  unacc
1     vhigh  vhigh      2     2  small   med  unacc
2     vhigh  vhigh      2     2  small  high  unacc
3     vhigh  vhigh      2     2    med   low  unacc
4     vhigh  vhigh      2     2    med   med  unacc
...     ...    ...    ...   ...    ...   ...    ...
1723    low    low  5more  more    med   med   good
1724    low    low  5more  more    med  high  vgood
1725    low    low  5more  more    big   low  unacc
1726    low    low  5more  more    big   med   good
1727    low    low  5more  more    big  high  vgood

[1728 rows x 7 columns]

# Exploratory Data Analysis

In [72]:
df.shape

(1728, 7)

In [73]:
df.head()

0      1  2  3      4     5      6
0  vhigh  vhigh  2  2  small   low  unacc
1  vhigh  vhigh  2  2  small   med  unacc
2  vhigh  vhigh  2  2  small  high  unacc
3  vhigh  vhigh  2  2    med   low  unacc
4  vhigh  vhigh  2  2    med   med  unacc

Rename Columns Names

In [74]:
col_names=["buying","maint","doors","persons","lug_boot","safety","class"]
df.columns=col_names

In [75]:
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [76]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1728 entries, 0 to 1727
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype 
---  ------    --------------  ----- 
 0   buying    1728 non-null   object
 1   maint     1728 non-null   object
 2   doors     1728 non-null   object
 3   persons   1728 non-null   object
 4   lug_boot  1728 non-null   object
 5   safety    1728 non-null   object
 6   class     1728 non-null   object
dtypes: object(7)
memory usage: 94.6+ KB


In [77]:
for col in col_names:
    print(df[col].value_counts())

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
maint
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64
doors
2        432
3        432
4        432
5more    432
Name: count, dtype: int64
persons
2       576
4       576
more    576
Name: count, dtype: int64
lug_boot
small    576
med      576
big      576
Name: count, dtype: int64
safety
low     576
med     576
high    576
Name: count, dtype: int64
class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64


In [78]:
df["class"].value_counts()

class
unacc    1210
acc       384
good       69
vgood      65
Name: count, dtype: int64

In [79]:
df.isnull().sum()

buying      0
maint       0
doors       0
persons     0
lug_boot    0
safety      0
class       0
dtype: int64

In [80]:
df.duplicated().sum()

np.int64(0)

# Declear Target Variable

In [81]:
X=df.drop(["class"],axis=1)
y=df["class"]

In [82]:
#split x and y into train and test 
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.33,random_state=42)


In [83]:
X_train.shape, X_test.shape

((1157, 6), (571, 6))

# Feature Engineering 

In [84]:
X_train.dtypes

buying      object
maint       object
doors       object
persons     object
lug_boot    object
safety      object
dtype: object

Encoding Using Category Encoders

In [85]:
import category_encoders as ce

In [86]:
encoder=ce.OrdinalEncoder(cols=["buying","maint","doors","persons","lug_boot","safety"])
X_train=encoder.fit_transform(X_train)
X_test=encoder.transform(X_test)

In [87]:
X_train.head()

buying  maint  doors  persons  lug_boot  safety
48         1      1      1        1         1       1
468        2      1      1        2         2       1
155        1      2      1        1         2       2
1721       3      3      2        1         2       2
1208       4      3      3        1         2       2

In [88]:
X_test.head()

buying  maint  doors  persons  lug_boot  safety
599        2      2      4        3         1       2
1201       4      3      3        2         1       3
628        2      2      2        3         3       3
1498       3      2      2        2         1       3
1263       4      3      4        1         1       1

 # Decision Tree Classifier using gini index


In [89]:
from sklearn.tree import DecisionTreeClassifier 

In [93]:
gini=DecisionTreeClassifier(criterion='gini', max_depth=100,random_state=0)

gini.fit(X_train,y_train)

DecisionTreeClassifier(max_depth=100, random_state=0)

In [94]:
y_pred_gini=gini.predict(X_test)

## Check accuracy score with gini index

In [100]:
from sklearn.metrics import accuracy_score

print("Model accuracy score with gigi index: {0:0.4f}".format(accuracy_score(y_test,y_pred_gini)))

Model accuracy score with gigi index: 0.9422


## Check OverFiting

In [102]:
y_pred_train_gini=gini.predict(X_train)


In [103]:
print("Model accuracy score with gigi index: {0:0.4f}".format(accuracy_score(y_train,y_pred_train_gini)))

Model accuracy score with gigi index: 1.0000


In [105]:
print("Training set score: {0:0.4f}".format(accuracy_score(y_train,y_pred_train_gini)))
print("Testing set score: {0:0.4f}".format(accuracy_score(y_test,y_pred_gini)))


Training set score: 1.0000
Testing set score: 0.9422


 # Decision Tree Classifier using entropy


In [121]:
entropy=DecisionTreeClassifier(criterion='entropy', max_depth=100,random_state=0)

entropy.fit(X_train,y_train)

DecisionTreeClassifier(criterion='entropy', max_depth=100, random_state=0)

In [122]:
y_pred_entropy=entropy.predict(X_test)

## Check accuracy score with Entropy

In [123]:
from sklearn.metrics import accuracy_score

print("Model accuracy score with Entropy: {0:0.4f}".format(accuracy_score(y_test,y_pred_entropy)))

Model accuracy score with Entropy: 0.9475


## Check OverFiting

In [124]:
y_pred_train_entropy=entropy.predict(X_train)


In [125]:
print("Model accuracy score with gigi index: {0:0.4f}".format(accuracy_score(y_train,y_pred_train_gini)))

Model accuracy score with gigi index: 1.0000


In [126]:
print("Training set score: {0:0.4f}".format(accuracy_score(y_train,y_pred_train_entropy)))
print("Testing set score: {0:0.4f}".format(accuracy_score(y_test,y_pred_entropy)))


Training set score: 1.0000
Testing set score: 0.9475


# Calculate Confusion Matrix

In [132]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test, y_pred_entropy)

print(cm)

[[109  12   8   0]
 [  0  20   0   0]
 [  7   0 390   0]
 [  3   0   0  22]]


# Saving The Model 

In [ ]:
import pickle


# Option 1: Using pickle
with open('model.pkl', 'wb') as file:
    pickle.dump(entropy, file)
    
with open('encoder.pkl', 'wb') as file:
    pickle.dump(encoder, file)

print("the model saved succesfully")

the model saved succesfully
